name: digigyan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+6

environment:
  sdk: '>=3.0.2 <4.0.0'


# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_lints: any

  cupertino_icons: any
  #  responsive_framework: ^0.2.0

  responsiveness: any
  permission_handler: any

  #  fl_chart: ^0.36.1

  #  fl_chart: ^0.55.2
  percent_indicator: any
  flutter_barcode_scanner: any


  shimmer: any

  connectivity_plus: any
  flutter_bloc: any
  equatable: any
  path_provider: any
  shared_preferences: any
  dio: any
  image_network: any
  image_picker: any
  badges: any
  get: any
  flutter_svg: ^2.0.7
  js: any
  riverpod: any
  flutter_riverpod: any
  intl: any
  grouped_list: any
  infinite_scroll_pagination: any
  readmore: any
  scrollable_positioned_list: any
  get_storage: any
  flutter_cache_manager: any
  font_awesome_flutter: any
  cached_network_image: any
  file_picker: any
  http: any
  webview_flutter: any
  flutter_widget_from_html_core: any
  fwfh_webview: any
  responsive_framework: any
  youtube_parser: any
  youtube_player_flutter: any
  youtube_explode_dart: any
  youtube_plyr_iframe: any
  url_launcher: any
  flutter_cached_pdfview: any
  octo_image: any
  internet_file: ^1.2.0
  carousel_slider: ^4.2.1
  flutter_image_slideshow: ^0.1.6
  flash_card: ^0.0.7
  cupertino_stepper: ^0.2.1
  pdf: ^3.10.4
  open_file: ^3.3.2
  #
  printing: ^5.11.0
  vector_math: ^2.1.4
  xml: ^6.3.0
  firebase_core: ^2.15.0
  firebase_app_check: 0.1.5+1
  cloud_firestore: ^4.8.3
  firebase_messaging: ^14.6.0
  flutter_local_notifications: 15.1.0+1
  custom_radio_grouped_button: ^2.2.1
  timer_count_down: ^2.2.0
  swipable_stack: ^2.0.0
  audioplayers: ^5.1.0
  video_player: ^2.7.1
  simple_barcode_scanner: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.
    #  drift_dev: ^1.3.0
    #  hive generator
  build_runner: any
#  flutter_lints: any
#  pdf_viewer_plugin: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/
    - assets/cbt_json/
    - assets/svg/
    #    - ASSETS/IMAGES/logo.png
    #    - ASSETS/IMAGES/login_bg.png
    #   - images/a_dot_ham.jpeg

flutter_icons:
  image_path: "DigiGyan.png"
  remove_alpha_ios: true
  android:
    generate: true
  ios:
    generate: true
  web:
    generate: true
  windows:
    generate: true
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # cbtpri:
  fonts:
    - family: Gopher
      fonts:
        - asset: assets/fonts/gopher_bold.ttf
          weight: 900
        - asset: assets/fonts/gopher_light.ttf
          weight: 300
        - asset: assets/fonts/gopher_thin.ttf
          weight: 100
        - asset: assets/fonts/gopher_medium.ttf
          weight: 500
        - asset: assets/fonts/gopher_regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 900
        - asset: assets/fonts/montserrat_thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat_light.ttf
          weight: 300
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat_semibold.ttf
          weight: 700
        - asset: assets/fonts/montserrat_regular.ttf

    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/league_bold.ttf
          weight: 900
        - asset: assets/fonts/league_thin.ttf
          weight: 100
        - asset: assets/fonts/league_light.ttf
          weight: 300
        - asset: assets/fonts/league_medium.ttf
          weight: 500
        - asset: assets/fonts/league_semibold.ttf
          weight: 700
        - asset: assets/fonts/league_regular.ttf

    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/montserrat_semibold.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/montserrat_bold.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/montserrat_light.ttf
    - family: MontserratThin
      fonts:
        - asset: assets/fonts/montserrat_thin.ttf

    - family: GopherRegular
      fonts:
        - asset: assets/fonts/gopher_regular.ttf
    #    - family: GopherSemiBold
    #      fonts:
    #        - asset: assets/fonts/_semibold.ttf
    - family: GopherBold
      fonts:
        - asset: assets/fonts/gopher_bold.ttf
    - family: GopherMedium
      fonts:
        - asset: assets/fonts/gopher_medium.ttf
    - family: GopherLight
      fonts:
        - asset: assets/fonts/gopher_light.ttf
    - family: GopherThin
      fonts:
        - asset: assets/fonts/gopher_thin.ttf

    - family: LeagueRegular
      fonts:
        - asset: assets/fonts/league_regular.ttf
    - family: LeagueBold
      fonts:
        - asset: assets/fonts/league_semibold.ttf
    - family: LeagueBold
      fonts:
        - asset: assets/fonts/league_bold.ttf
    - family: LeagueMedium
      fonts:
        - asset: assets/fonts/league_medium.ttf
    - family: LeagueLight
      fonts:
        - asset: assets/fonts/league_light.ttf
    - family: LeagueThin
      fonts:
        - asset: assets/fonts/league_thin.ttf

    - family: hindiF
      fonts:
        - asset: assets/fonts/KRDEV010.TTF



    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # cbtpri:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#  module:
#    androidX: true
#    androidPackage: com.cbtpri.pdf_test
#    iosBundleIdentifier: com.cbtpri.pdfTest
